version: "3.7"
services:
  db:
    image: postgres
    environment:
      - PGDATA=/db-data
    volumes:
      - db:/db-data:rw
  app:
    image: babybuddy/babybuddy
    # See README.md#configuration for other environment configuration options.
    environment:
      - ALLOWED_HOSTS=
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.docker
      - SECRET_KEY=
      - TIME_ZONE=
    volumes:
      - media:/app/media:rw
    command: gunicorn -c /app/gunicorn.py babybuddy.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db: {}
  media: {}
