version: "2"

services:
  db:
    image: postgres
    environment:
       - PGDATA=/db-data
    volumes:
       - db:/db-data
  app:
    image: cosme/babybuddy
    env_file: 
      - /path/to/docker.env
    command: gunicorn -c /app/gunicorn.py babybuddy.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
   db:
